#+TITLE: How to cfg cscope for emacs24

* install cscope
#+BEGIN_SRC sh
sudo apt-get install cscope
#+END_SRC

* install xcscope by using package
+ list enable packages
#+BEGIN_SRC emacs
M-x package-list-packages
#+END_SRC

+ search xcscope
+ click xcscope 
+ click install
#+BEGIN_SRC info
xcscope is an available package.

     Status: Available from melpa -- Install
    Archive: melpa
    Version: 20140510.1437
    Summary: cscope interface for (X)Emacs
   Homepage: https://github.com/dkogan/xcscope.el
   Keywords: languages c 
#+END_SRC

* config .emacs
#+BEGIN_SRC lisp
(require 'xcscope)
#+END_SRC

Restart (X)Emacs.  That's it.

* Keybindings

All keybindings use the "C-c s" prefix, but are usable only while
editing a source file, or in the cscope results buffer:

     C-c s s         Find symbol.
     C-c s =         Find assignments to this symbol
     C-c s d         Find global definition.
     C-c s g         Find global definition (alternate binding).
     C-c s G         Find global definition without prompting.
     C-c s c         Find functions calling a function.
     C-c s C         Find called functions (list functions called
                     from a function).
     C-c s t         Find text string.
     C-c s e         Find egrep pattern.
     C-c s f         Find a file.
     C-c s i         Find files #including a file.

These pertain to navigation through the search results:

     C-c s b         Display *cscope* buffer.
     C-c s B         Auto display *cscope* buffer toggle.
     C-c s n         Next symbol.
     C-c s N         Next file.
     C-c s p         Previous symbol.
     C-c s P         Previous file.
     C-c s u         Pop mark.

These pertain to setting and unsetting the variable,
`cscope-initial-directory', (location searched for the cscope database
 directory):

     C-c s a         Set initial directory.
     C-c s A         Unset initial directory.

These pertain to cscope database maintenance:

     C-c s L         Create list of files to index.
     C-c s I         Create list and index.
     C-c s E         Edit list of files to index.
     C-c s W         Locate this buffer's cscope directory
                     ("W" --> "where").
     C-c s S         Locate this buffer's cscope directory.
                     (alternate binding: "S" --> "show").
     C-c s T         Locate this buffer's cscope directory.
                     (alternate binding: "T" --> "tell").
     C-c s D         Dired this buffer's directory.	 
